name: main-pull-request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Assigning SIMPLE_REPOSITORY_NAME
        run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Assigning SIMPLE_BRANCH_NAME
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          SIMPLE_BRANCH_NAME="${BRANCH_NAME//\//-}"
          echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout ${{ env.SIMPLE_BRANCH_NAME }} branch
        uses: actions/checkout@v4
        with:
          path: main-project

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "main-project/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: main-project

      - name: Lint
        run: npm run lint
        working-directory: main-project

      - name: Build
        run: npm run build
        working-directory: main-project

      - name: Test with coverage
        run: npm run test:coverage
        working-directory: main-project

      - name: Upload Jest Code Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: main-project/coverage/lcov-report/
